name: x86-64 Pull and Save Docker Image
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest'  # 设置默认的 Docker 镜像列表

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: init
      uses: actions/checkout@v4

    - name: list images
      run: docker images

    - name: pull james
      run: docker pull apache/james:jpa-latest

    - name: list images2
      run: docker images

    - name: save
      run: docker save apache/james:jpa-latest > james-jpa.tar

    - name: upload
      run: docker save apache/james:jpa-latest > james-jpa.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar
        path: james-jpa.tar
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天


