name: x86-64 Pull and Save Docker Image
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest'  # 设置默认的 Docker 镜像列表

jobs:
  pull_and_package:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: docker images
      run: docker images

    - name: docker ver
      run: docker version

    - name: Pull Docker Images and Package
      run: cmd ver

    - name: Compress the TAR files
      run: tar -czf x86-64-images.tar.gz *-amd64.tar

