name: x86-64 Pull and Save Docker Image
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest'  # 设置默认的 Docker 镜像列表

jobs:
  pull_and_package:
    runs-on: windows-latest

    steps:
    - name: init
      uses: actions/checkout@v4

    - name: list images
      run: docker images

    - name: pull james
      run: docker pull apache/james:jpa-latest

    - name: list images2
      run: docker images

